// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'api_key2',
    appId: '1:485290725277:web:ad8e0f8735fc9dcfb0a974',
    messagingSenderId: '485290725277',
    projectId: 'fivekdatabase',
    authDomain: 'fivekdatabase.firebaseapp.com',
    storageBucket: 'fivekdatabase.firebasestorage.app',
    measurementId: 'G-E7DWWNSP5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'api_key3',
    appId: '1:485290725277:android:08136ba522bc8898b0a974',
    messagingSenderId: '485290725277',
    projectId: 'fivekdatabase',
    storageBucket: 'fivekdatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'api_key4',
    appId: '1:485290725277:ios:bd2cce07d7fff200b0a974',
    messagingSenderId: '485290725277',
    projectId: 'fivekdatabase',
    storageBucket: 'fivekdatabase.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'api_key4',
    appId: '1:485290725277:ios:bd2cce07d7fff200b0a974',
    messagingSenderId: '485290725277',
    projectId: 'fivekdatabase',
    storageBucket: 'fivekdatabase.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'api_key2',
    appId: '1:485290725277:web:38d84d7d15c70041b0a974',
    messagingSenderId: '485290725277',
    projectId: 'fivekdatabase',
    authDomain: 'fivekdatabase.firebaseapp.com',
    storageBucket: 'fivekdatabase.firebasestorage.app',
    measurementId: 'G-8CG4XRHP06',
  );
}
